In [31]:
import cv2
import numpy as np
#创建一个大小800*800的空帧
frame = np.zeros((800,800,3),np.uint8)
#初始化测量坐标和鼠标运动预测的数组
last_measurement = current_measurement = np.array((0,0),np.float32)
last_predicition = current_prediction = np.array((0,0,0,0),np.float32).reshape(4,1)
#print(last_measurement)
'''
    mousemove()函数在这里的作用就是传递X,Y的坐标值，便于对轨迹进行卡尔曼滤波
'''
def mousemove(event,x,y,s,p):
    #定义全局变量
    global frame,current_measurement,measurements,last_measurement,current_prediction,last_prediction
    #初始化
    last_measurement = current_measurement
    last_prediction = current_prediction
    print(last_prediction)
    #传递当前测量坐标值
    current_measurement = np.array([[np.float32(x)],[np.float32(y)]])
    #用来修正卡尔曼滤波的预测结果
    kalman.correct(current_measurement)
    # 调用kalman这个类的predict方法得到状态的预测值矩阵，用来估算目标位置
    current_prediction = kalman.predict()
    #上一次测量值
    lmx,lmy = last_measurement[0],last_measurement[1]
    #当前测量值
    cmx,cmy = current_measurement[0],current_measurement[1]
    #上一次预测值
    lpx,lpy = last_prediction[0],last_prediction[1]
    #当前预测值
    cpx,cpy = current_prediction[0],current_prediction[1]
    #绘制测量值轨迹（绿色）
    #print(lpx,lpy,cpx,cpy)
    cv2.line(frame,(lmx,lmy),(cmx,cmy),(0,100,0))
    #绘制预测值轨迹（红色）
    cv2.line(frame,(lpx,lpy),(cpx,cpy),(0,0,200))
 
cv2.namedWindow("kalman_tracker")
#调用函数处理鼠标事件，具体事件必须由回调函数的第一个参数来处理，该参数确定触发事件的类型（点击和移动）
'''
void setMousecallback(const string& winname, MouseCallback onMouse, void* userdata=0)
       winname:窗口的名字
       onMouse:鼠标响应函数，回调函数。指定窗口里每次鼠标时间发生的时候，被调用的函数指针。
                这个函数的原型应该为void on_Mouse(int event, int x, int y, int flags, void* param);
       userdate：传给回调函数的参数
 void on_Mouse(int event, int x, int y, int flags, void* param);
        event是 CV_EVENT_*变量之一
        x和y是鼠标指针在图像坐标系的坐标（不是窗口坐标系）
        flags是CV_EVENT_FLAG的组合， param是用户定义的传递到setMouseCallback函数调用的参数。
    常用的event：
        CV_EVENT_MOUSEMOVE
        CV_EVENT_LBUTTONDOWN
        CV_EVENT_RBUTTONDOWN
        CV_EVENT_LBUTTONUP
        CV_EVENT_RBUTTONUP
        和标志位flags有关的：
        CV_EVENT_FLAG_LBUTTON
'''
cv2.setMouseCallback("kalman_tracker",mousemove)
'''
Kalman这个类需要初始化下面变量：
转移矩阵，测量矩阵，控制向量(没有的话，就是0)，
过程噪声协方差矩阵，测量噪声协方差矩阵，
后验错误协方差矩阵，前一状态校正后的值，当前观察值。
    在此cv2.KalmanFilter(4,2)表示转移矩阵维度为4，测量矩阵维度为2
卡尔曼滤波模型假设k时刻的真实状态是从(k − 1)时刻的状态演化而来，符合下式：
            X(k) = F(k) * X(k-1) + B(k)*U(k) + W（k）
其中
F(k)  是作用在xk−1上的状态变换模型（/矩阵/矢量）。 
B(k)  是作用在控制器向量uk上的输入－控制模型。 
W(k)  是过程噪声，并假定其符合均值为零，协方差矩阵为Qk的多元正态分布。
'''
kalman = cv2.KalmanFilter(4,2)
#设置测量矩阵
kalman.measurementMatrix = np.array([[1,0,0,0],[0,1,0,0]],np.float32)
#设置转移矩阵
kalman.transitionMatrix = np.array([[1,0,1,0],[0,1,0,1],[0,0,1,0],[0,0,0,1]],np.float32)
#设置过程噪声协方差矩阵
kalman.processNoiseCov = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],np.float32)*0.03
 
while True:
    cv2.imshow("kalman_tracker",frame)
    if (cv2.waitKey(30) & 0xff) == 27:
        break
 
cv2.destroyAllWindows()

[[0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[23.184465]
 [ 6.029126]
 [ 0.      ]
 [ 0.      ]]
[[107.49456 ]
 [ 27.901497]
 [ 21.232126]
 [  5.508201]]
[[303.62033 ]
 [ 78.337875]
 [ 69.71617 ]
 [ 17.9632  ]]
[[573.6709  ]
 [148.0599  ]
 [121.69306 ]
 [ 31.392065]]
[[805.9353  ]
 [207.7953  ]
 [148.19795 ]
 [ 38.186203]]
[[942.9205 ]
 [242.15944]
 [145.664  ]
 [ 37.32246]]
[[996.8163  ]
 [255.7145  ]
 [125.61224 ]
 [ 32.129177]]
[[997.0531  ]
 [254.89618 ]
 [ 98.59833 ]
 [ 25.030172]]
[[968.76855 ]
 [247.40094 ]
 [ 71.33464 ]
 [ 18.041344]]
[[928.8973  ]
 [236.64468 ]
 [ 47.39706 ]
 [ 11.842528]]
[[887.54565  ]
 [225.3241   ]
 [ 28.245178 ]
 [  6.8439507]]
[[849.8913   ]
 [214.99774  ]
 [ 13.997882 ]
 [  3.1317763]]
[[8.1937903e+02]
 [2.0698737e+02]
 [4.3654737e+00]
 [7.2051162e-01]]
[[ 7.9651483e+02]
 [ 2.0125706e+02]
 [-1.5295084e+00]
 [-6.7603177e-01]]
[[780.58405  ]
 [196.90532  ]
 [ -4.6474524]
 [ -1.471843 ]]
[[770.30493  ]
 [194.31389  ]
 [ -5.8666873]
 [ -1.7142284]]
[[

[[357.37946  ]
 [251.818    ]
 [  2.073979 ]
 [  1.0223082]]
[[358.05502  ]
 [251.18416  ]
 [  1.7712595]
 [  0.6637972]]
[[3.5685541e+02]
 [2.4997659e+02]
 [1.1281488e+00]
 [2.5870186e-01]]
[[ 3.5454230e+02]
 [ 2.4848593e+02]
 [ 3.8321149e-01]
 [-1.1998657e-01]]
[[ 3.5166824e+02]
 [ 2.4749265e+02]
 [-3.2189125e-01]
 [-3.0902991e-01]]
[[348.60278   ]
 [246.30637   ]
 [ -0.915795  ]
 [ -0.49892738]]
[[344.9819   ]
 [245.03967  ]
 [ -1.5013708]
 [ -0.665126 ]]
[[339.96494  ]
 [243.76352  ]
 [ -2.262401 ]
 [ -0.7973954]]
[[335.3723    ]
 [243.10512   ]
 [ -2.7668285 ]
 [ -0.76730984]]
[[330.62357   ]
 [242.86374   ]
 [ -3.1958616 ]
 [ -0.65346104]]
[[325.2981   ]
 [242.87805  ]
 [ -3.6568592]
 [ -0.5089035]]
[[ 3.1911520e+02]
 [ 2.4361624e+02]
 [-4.2036719e+00]
 [-2.3894478e-01]]
[[ 3.1366840e+02]
 [ 2.4477824e+02]
 [-4.4727726e+00]
 [ 6.4321995e-02]]
[[308.8028    ]
 [246.14832   ]
 [ -4.5578074 ]
 [  0.34697846]]
[[303.77316   ]
 [248.17125   ]
 [ -4.6599407 ]
 [  0.70977575]]
[[299.246

 [-5.96623182e+00]]
[[ 1.1145085e+02]
 [ 3.4574408e+02]
 [ 1.3943434e-01]
 [-5.8768373e+00]]
[[ 1.12500725e+02]
 [ 3.40017670e+02]
 [ 3.36520284e-01]
 [-5.84427834e+00]]
[[113.718376  ]
 [334.75073   ]
 [  0.52726126]
 [ -5.719304  ]]
[[114.998856  ]
 [329.76562   ]
 [  0.69031215]
 [ -5.5603695 ]]
[[116.86525   ]
 [325.51843   ]
 [  0.94490194]
 [ -5.276108  ]]
[[119.06476  ]
 [320.52533  ]
 [  1.2164894]
 [ -5.214842 ]]
[[122.00631  ]
 [315.58945  ]
 [  1.5899171]
 [ -5.1544533]]
[[125.35564  ]
 [311.26398  ]
 [  1.9707807]
 [ -4.975    ]]
[[128.29282  ]
 [306.72156  ]
 [  2.17998  ]
 [ -4.8813615]]
[[130.88841  ]
 [303.17926  ]
 [  2.2699494]
 [ -4.591493 ]]
[[133.81165  ]
 [299.6578   ]
 [  2.411368 ]
 [ -4.3598547]]
[[136.33371  ]
 [297.26218  ]
 [  2.4353306]
 [ -3.9346538]]
[[139.74834  ]
 [294.93655  ]
 [  2.6473196]
 [ -3.586342 ]]
[[142.54356  ]
 [293.7383   ]
 [  2.6793368]
 [ -3.069382 ]]
[[145.49115  ]
 [292.58585  ]
 [  2.7374055]
 [ -2.654423 ]]
[[148.5276   ]
 [291.3502

[[433.4026   ]
 [354.8379   ]
 [ -6.657873 ]
 [ -0.7612716]]
[[ 4.2650812e+02]
 [ 3.5593503e+02]
 [-6.7090912e+00]
 [-3.5898137e-01]]
[[ 4.1950040e+02]
 [ 3.5737735e+02]
 [-6.7737350e+00]
 [ 3.0950811e-02]]
[[ 4.1243256e+02]
 [ 3.5894968e+02]
 [-6.8373966e+00]
 [ 3.6460990e-01]]
[[405.92865  ]
 [360.5193   ]
 [ -6.7652054]
 [  0.6254564]]
[[399.7931   ]
 [362.6027   ]
 [ -6.628906 ]
 [  0.9410579]]
[[393.87347  ]
 [365.54037  ]
 [ -6.4753604]
 [  1.3732706]]
[[388.64786  ]
 [368.9469   ]
 [ -6.204819 ]
 [  1.8134115]]
[[383.8254   ]
 [372.55466  ]
 [ -5.905575 ]
 [  2.2018332]]
[[379.78555  ]
 [376.78134  ]
 [ -5.5016966]
 [  2.640157 ]]
[[376.7607   ]
 [380.72543  ]
 [ -4.9655256]
 [  2.9224193]]
[[374.28662  ]
 [385.57233  ]
 [ -4.4261947]
 [  3.3390167]]
[[372.63052  ]
 [390.3381   ]
 [ -3.8265486]
 [  3.6478703]]
[[371.37195  ]
 [395.55038  ]
 [ -3.2706547]
 [  3.9865222]]
[[370.82123  ]
 [400.97656  ]
 [ -2.6818643]
 [  4.298167 ]]
[[370.59525  ]
 [407.05164  ]
 [ -2.150232 ]
 [  

 [  3.9489481]]
[[433.0803   ]
 [603.36346  ]
 [  4.5139337]
 [  3.821035 ]]
[[434.60852  ]
 [606.3832   ]
 [  3.8676083]
 [  3.647572 ]]
[[436.35538  ]
 [609.80554  ]
 [  3.4085248]
 [  3.5988233]]
[[437.79193  ]
 [612.34326  ]
 [  2.9816465]
 [  3.3691185]]
[[439.13275  ]
 [614.923    ]
 [  2.6264513]
 [  3.198226 ]]
[[441.09348  ]
 [617.5788   ]
 [  2.4823403]
 [  3.0808034]]
[[443.5209   ]
 [620.3194   ]
 [  2.4704483]
 [  3.0071678]]
[[446.27292  ]
 [623.13885  ]
 [  2.5313997]
 [  2.9665334]]
[[449.81934  ]
 [626.6115   ]
 [  2.7511227]
 [  3.07609  ]]
[[453.26434  ]
 [629.3282   ]
 [  2.9013293]
 [  2.9982924]]
[[457.18573  ]
 [632.1336   ]
 [  3.1221433]
 [  2.9565399]]
[[460.78644  ]
 [634.4239   ]
 [  3.2257364]
 [  2.8123202]]
[[464.13766 ]
 [635.8117  ]
 [  3.252906]
 [  2.503948]]
[[468.48508  ]
 [637.25085  ]
 [  3.4898362]
 [  2.273459 ]]
[[472.27756  ]
 [638.7892   ]
 [  3.5553458]
 [  2.1143227]]
[[476.84518  ]
 [639.852    ]
 [  3.7744784]
 [  1.8866988]]
[[480.71066 

 [  2.2680128]]
[[594.0616   ]
 [595.43646  ]
 [ -8.688268 ]
 [  2.2160337]]
[[581.8109  ]
 [597.9837  ]
 [ -9.459435]
 [  2.287728]]
[[568.93634  ]
 [599.6933   ]
 [-10.198712 ]
 [  2.1625793]]
[[555.8365   ]
 [600.8607   ]
 [-10.826724 ]
 [  1.9471543]]
[[542.16736  ]
 [601.71436  ]
 [-11.442032 ]
 [  1.7104299]]
[[528.8639  ]
 [602.41724 ]
 [-11.84499 ]
 [  1.492326]]
[[515.9235   ]
 [603.07666  ]
 [-12.082118 ]
 [  1.3120222]]
[[502.71094  ]
 [603.1682   ]
 [-12.326833 ]
 [  1.0478251]]
[[489.9663   ]
 [603.5295   ]
 [-12.41728  ]
 [  0.8992026]]
[[477.56882   ]
 [603.5298    ]
 [-12.412993  ]
 [  0.70461893]]
[[ 4.6540924e+02]
 [ 6.0333533e+02]
 [-1.2358137e+01]
 [ 5.0999641e-01]]
[[ 4.5398599e+02]
 [ 6.0306055e+02]
 [-1.2155757e+01]
 [ 3.4011328e-01]]
[[ 4.4301389e+02]
 [ 6.0277740e+02]
 [-1.1899530e+01]
 [ 2.0518827e-01]]
[[ 4.3286932e+02]
 [ 6.0252570e+02]
 [-1.1519630e+01]
 [ 1.0628520e-01]]
[[ 4.2318961e+02]
 [ 6.0232306e+02]
 [-1.1121339e+01]
 [ 3.9405074e-02]]
[[ 4.1489539e

 [ 1.8356217e-01]]
[[ 3.7026837e+02]
 [ 6.9183514e+02]
 [-2.4307694e+00]
 [ 2.9107666e-01]]
[[ 3.6826761e+02]
 [ 6.9222314e+02]
 [-2.3376901e+00]
 [ 3.1204998e-01]]
[[ 3.6636035e+02]
 [ 6.9240405e+02]
 [-2.2445138e+00]
 [ 2.8366107e-01]]
[[ 3.6449176e+02]
 [ 6.9303796e+02]
 [-2.1631362e+00]
 [ 3.5947874e-01]]
[[ 3.6321503e+02]
 [ 6.9337518e+02]
 [-1.9712548e+00]
 [ 3.5464889e-01]]
[[ 3.6170511e+02]
 [ 6.9350934e+02]
 [-1.8713889e+00]
 [ 3.0691731e-01]]
[[ 3.6059473e+02]
 [ 6.9351691e+02]
 [-1.7066501e+00]
 [ 2.4211821e-01]]
[[ 3.5971396e+02]
 [ 6.9404297e+02]
 [-1.5278683e+00]
 [ 3.0357835e-01]]
[[ 3.5894189e+02]
 [ 6.9432129e+02]
 [-1.3642554e+00]
 [ 2.9811177e-01]]
[[ 3.5819949e+02]
 [ 6.9501831e+02]
 [-1.2296411e+00]
 [ 3.8445881e-01]]
[[ 3.5744031e+02]
 [ 6.9539203e+02]
 [-1.1277989e+00]
 [ 3.8212931e-01]]
[[ 3.5664145e+02]
 [ 6.9554376e+02]
 [-1.0565937e+00]
 [ 3.3225459e-01]]
[[ 3.5579556e+02]
 [ 6.9555646e+02]
 [-1.0109780e+00]
 [ 2.6307601e-01]]
[[ 3.5490475e+02]
 [ 6.9608020e+

 [ -2.2269726]]
[[ 65.41291  ]
 [576.187    ]
 [ -0.8888327]
 [ -2.3547227]]
[[ 64.86912  ]
 [572.547    ]
 [ -0.8141419]
 [ -2.632959 ]]
[[ 64.1319    ]
 [569.0049    ]
 [ -0.79749084]
 [ -2.829771  ]]
[[ 63.844597 ]
 [564.9968   ]
 [ -0.6870489]
 [ -3.0848365]]
[[ 63.24888  ]
 [560.1507   ]
 [ -0.6672782]
 [ -3.466099 ]]
[[ 63.023037  ]
 [555.42065   ]
 [ -0.57171893]
 [ -3.739715  ]]
[[ 6.3025486e+01]
 [ 5.5084601e+02]
 [-4.4742763e-01]
 [-3.9204538e+00]]
[[ 6.3150787e+01]
 [ 5.4701605e+02]
 [-3.2344791e-01]
 [-3.9008627e+00]]
[[ 6.3326427e+01]
 [ 5.4310577e+02]
 [-2.1540929e-01]
 [-3.9029050e+00]]
[[ 6.2919174e+01]
 [ 5.3914069e+02]
 [-2.5693807e-01]
 [-3.9163618e+00]]
[[ 6.2709740e+01]
 [ 5.3514166e+02]
 [-2.4665524e-01]
 [-3.9342601e+00]]
[[ 6.2633671e+01]
 [ 5.3112415e+02]
 [-2.0972772e-01]
 [-3.9522827e+00]]
[[ 6.2639236e+01]
 [ 5.2651123e+02]
 [-1.6312255e-01]
 [-4.0952988e+00]]
[[ 6.2688137e+01]
 [ 5.2270319e+02]
 [-1.1722545e-01]
 [-4.0331163e+00]]
[[ 6.2166489e+01]
 [ 5.188

 [-2.1078892e-02]]
[[1.3838104e+02]
 [2.2688583e+02]
 [1.0987902e+00]
 [7.6439208e-03]]
[[1.3925589e+02]
 [2.2696057e+02]
 [1.0503131e+00]
 [2.2168392e-02]]
[[1.4015582e+02]
 [2.2700592e+02]
 [1.0177583e+00]
 [2.7184596e-02]]
[[1.4166971e+02]
 [2.2702962e+02]
 [1.1251563e+00]
 [2.6431389e-02]]
[[1.4298898e+02]
 [2.2703864e+02]
 [1.1671767e+00]
 [2.2663413e-02]]
[[1.4416263e+02]
 [2.2703859e+02]
 [1.1685783e+00]
 [1.7748155e-02]]
[[1.4523563e+02]
 [2.2703365e+02]
 [1.1478884e+00]
 [1.2838720e-02]]
[[1.4624503e+02]
 [2.2702672e+02]
 [1.1179116e+00]
 [8.5582528e-03]]
[[1.4663123e+02]
 [2.2760728e+02]
 [9.5951682e-01]
 [1.3238122e-01]]
[[1.4721977e+02]
 [2.2797046e+02]
 [8.7921095e-01]
 [1.8234330e-01]]
[[1.4796983e+02]
 [2.2817015e+02]
 [8.5125107e-01]
 [1.8610157e-01]]
[[1.4883881e+02]
 [2.2825626e+02]
 [8.5508895e-01]
 [1.6445464e-01]]
[[149.78864   ]
 [228.85782   ]
 [  0.87559634]
 [  0.2590753 ]]
[[150.78845   ]
 [229.20045   ]
 [  0.9024866 ]
 [  0.27716392]]
[[151.81526   ]
 [229.9

[[ 2.5839661e+02]
 [ 2.3446899e+02]
 [-1.2409559e+00]
 [-2.1107513e-01]]
[[258.098     ]
 [233.9823    ]
 [ -1.0369688 ]
 [ -0.27074155]]
[[258.76657   ]
 [233.72195   ]
 [ -0.66776925]
 [ -0.2684897 ]]
[[ 2.5999911e+02]
 [ 2.3361688e+02]
 [-2.5640562e-01]
 [-2.3311614e-01]]
[[ 2.6209406e+02]
 [ 2.3302122e+02]
 [ 2.5259539e-01]
 [-3.1159720e-01]]
[[264.05447  ]
 [232.69714  ]
 [  0.6222958]
 [ -0.3142975]]
[[266.40787   ]
 [231.97313   ]
 [  0.9970318 ]
 [ -0.40298957]]
[[268.9283   ]
 [231.58594  ]
 [  1.3268083]
 [ -0.399571 ]]
[[272.06036  ]
 [231.42972  ]
 [  1.7175946]
 [ -0.3468931]]
[[275.5056    ]
 [230.83028   ]
 [  2.0915813 ]
 [ -0.40156272]]
[[277.88776   ]
 [230.52846   ]
 [  2.154478  ]
 [ -0.37997013]]
[[279.5205    ]
 [230.42561   ]
 [  2.0415359 ]
 [ -0.31997952]]
[[281.25613   ]
 [229.8555    ]
 [  1.9753158 ]
 [ -0.37412694]]
[[282.49323   ]
 [229.5663    ]
 [  1.8155078 ]
 [ -0.35574326]]
[[283.43115   ]
 [228.87773   ]
 [  1.6255366 ]
 [ -0.42778906]]
[[284.80328  

 [ -0.36182588]]
[[ 3.0343182e+02]
 [ 7.7145676e+01]
 [ 3.9949408e+00]
 [-2.0985374e-01]]
[[ 3.04234436e+02]
 [ 7.74379120e+01]
 [ 3.30389261e+00]
 [-1.01164795e-01]]
[[3.0504971e+02]
 [7.8254791e+01]
 [2.7651787e+00]
 [9.7567335e-02]]
[[306.02255   ]
 [ 79.37803   ]
 [  2.3771877 ]
 [  0.31959647]]
[[306.62335   ]
 [ 80.06316   ]
 [  1.9926522 ]
 [  0.39872494]]
[[3.0766196e+02]
 [7.9249352e+01]
 [1.7861259e+00]
 [1.3624491e-01]]
[[ 3.0847131e+02]
 [ 7.8651344e+01]
 [ 1.5746883e+00]
 [-2.2700220e-02]]
[[309.1813    ]
 [ 77.070435  ]
 [  1.3875047 ]
 [ -0.36000982]]
[[309.87454  ]
 [ 75.49362  ]
 [  1.2372166]
 [ -0.6234149]]
[[311.1855    ]
 [ 73.99239   ]
 [  1.2531776 ]
 [ -0.81343657]]
[[311.74194  ]
 [ 72.00802  ]
 [  1.1023576]
 [ -1.066913 ]]
[[312.99597  ]
 [ 70.34869  ]
 [  1.1351881]
 [ -1.1951553]]
[[314.13354  ]
 [ 68.9486   ]
 [  1.1357006]
 [ -1.2395159]]
[[315.77847  ]
 [ 67.73929  ]
 [  1.2459328]
 [ -1.2329768]]
[[316.5669   ]
 [ 66.65954  ]
 [  1.1468939]
 [ -1.199808

 [  1.9213265]]
[[547.75555  ]
 [209.38596  ]
 [  2.1301577]
 [  2.0865273]]
[[550.02936  ]
 [211.83336  ]
 [  2.1612566]
 [  2.1646473]]
[[552.76105  ]
 [215.27136  ]
 [  2.2847438]
 [  2.4402921]]
[[554.5985   ]
 [218.72758  ]
 [  2.1879218]
 [  2.660213 ]]
[[557.0224   ]
 [223.31102  ]
 [  2.239    ]
 [  3.0765367]]
[[559.83594  ]
 [227.38019  ]
 [  2.3633723]
 [  3.2914124]]
[[561.708    ]
 [232.21127  ]
 [  2.2570226]
 [  3.6247103]]
[[563.5489   ]
 [236.88724  ]
 [  2.1669483]
 [  3.8522758]]
[[565.98096  ]
 [240.80579  ]
 [  2.2243395]
 [  3.8666217]]
[[567.6288 ]
 [244.78654]
 [  2.09954]
 [  3.89133]]
[[569.35876  ]
 [248.80333  ]
 [  2.0195448]
 [  3.918486 ]]
[[571.1674   ]
 [253.4251   ]
 [  1.973902 ]
 [  4.0707293]]
[[572.4552   ]
 [257.246    ]
 [  1.8253804]
 [  4.016648 ]]
[[574.01306  ]
 [261.11807  ]
 [  1.7674689]
 [  3.9853508]]
[[575.1852   ]
 [265.62177  ]
 [  1.6385851]
 [  4.0975513]]
[[575.53955  ]
 [269.3539   ]
 [  1.3605818]
 [  4.0184493]]
[[575.99536  ]
 

 [ 1.0873273e-01]]
[[ 5.9440796e+02]
 [ 5.0129773e+02]
 [-2.8163314e+00]
 [ 5.0413538e-02]]
[[ 5.9017645e+02]
 [ 5.0117319e+02]
 [-3.1226771e+00]
 [ 1.2535765e-02]]
[[ 5.8636237e+02]
 [ 5.0108395e+02]
 [-3.2723479e+00]
 [-9.4974823e-03]]
[[ 5.8287708e+02]
 [ 5.0102512e+02]
 [-3.3184488e+00]
 [-2.0178270e-02]]
[[ 5.7963086e+02]
 [ 5.0099017e+02]
 [-3.3028100e+00]
 [-2.3373576e-02]]
[[ 5.7654498e+02]
 [ 5.0097256e+02]
 [-3.2558472e+00]
 [-2.2123408e-02]]
[[ 5.7355658e+02]
 [ 5.0096655e+02]
 [-3.1979589e+00]
 [-1.8633030e-02]]
[[ 5.7120691e+02]
 [ 5.0096759e+02]
 [-3.0143239e+00]
 [-1.4377799e-02]]
[[ 5.6924640e+02]
 [ 5.0097226e+02]
 [-2.7862031e+00]
 [-1.0254573e-02]]
[[ 5.6749078e+02]
 [ 5.0097833e+02]
 [-2.5631063e+00]
 [-6.7253709e-03]]
[[ 5.6581464e+02]
 [ 5.0098434e+02]
 [-2.3711007e+00]
 [-3.9687883e-03]]
[[ 5.6472791e+02]
 [ 5.0098956e+02]
 [-2.0930741e+00]
 [-1.9770605e-03]]
[[ 5.6397015e+02]
 [ 5.0099371e+02]
 [-1.8040134e+00]
 [-6.4924185e-04]]
[[ 5.6277142e+02]
 [ 5.0099677e+

[[ 5.5311646e+02]
 [ 2.4989372e+02]
 [-4.0807014e+00]
 [ 2.3969775e-01]]
[[ 5.4955499e+02]
 [ 2.5078360e+02]
 [-3.9682949e+00]
 [ 3.8044071e-01]]
[[545.26056  ]
 [252.46663  ]
 [ -4.0389023]
 [  0.6624158]]
[[541.65625  ]
 [254.61792  ]
 [ -3.944829 ]
 [  0.9847166]]
[[537.32574  ]
 [257.0026   ]
 [ -4.0283184]
 [  1.2877698]]
[[533.10596  ]
 [258.87656  ]
 [ -4.0697603]
 [  1.4146619]]
[[528.3862   ]
 [260.95148  ]
 [ -4.2104626]
 [  1.5575887]]
[[524.5365   ]
 [263.71298  ]
 [ -4.1323776]
 [  1.8182061]]
[[520.0888   ]
 [266.28757  ]
 [ -4.200632 ]
 [  1.9819431]]
[[515.836    ]
 [268.6882   ]
 [ -4.2119303]
 [  2.0725803]]
[[511.13275 ]
 [271.53174 ]
 [ -4.318288]
 [  2.23947 ]]
[[507.32416  ]
 [274.63412  ]
 [ -4.207955 ]
 [  2.4262652]]
[[502.9257   ]
 [277.86313  ]
 [ -4.249195 ]
 [  2.6000347]]
[[498.72015  ]
 [280.5436   ]
 [ -4.2397413]
 [  2.6174479]]
[[494.6449   ]
 [283.4293   ]
 [ -4.2041388]
 [  2.675511 ]]
[[490.64944  ]
 [286.44022  ]
 [ -4.158962 ]
 [  2.7481177]]
[[48

 [-4.2655849e-01]]
[[ 5.6577515e+02]
 [ 1.9147006e+02]
 [ 4.4592104e+00]
 [-3.9466172e-01]]
[[ 5.6977881e+02]
 [ 1.9138686e+02]
 [ 4.3605947e+00]
 [-3.2724193e-01]]
[[ 5.7368170e+02]
 [ 1.9141997e+02]
 [ 4.2615132e+00]
 [-2.4923646e-01]]
[[ 5.7754260e+02]
 [ 1.9151161e+02]
 [ 4.1747856e+00]
 [-1.7544353e-01]]
[[ 5.8198621e+02]
 [ 1.9103549e+02]
 [ 4.2329769e+00]
 [-2.4053188e-01]]
[[ 5.8622729e+02]
 [ 1.9077411e+02]
 [ 4.2347317e+00]
 [-2.4504724e-01]]
[[ 5.9032843e+02]
 [ 1.9066182e+02]
 [ 4.2058148e+00]
 [-2.1630889e-01]]
[[ 5.9434119e+02]
 [ 1.9005655e+02]
 [ 4.1640310e+00]
 [-3.0050695e-01]]
[[ 5.9771698e+02]
 [ 1.8913510e+02]
 [ 3.9934025e+00]
 [-4.3492335e-01]]
[[ 6.0128900e+02]
 [ 1.8803308e+02]
 [ 3.9021869e+00]
 [-5.7933331e-01]]
[[604.43365  ]
 [186.2589   ]
 [  3.7381973]
 [ -0.8379862]]
[[607.3293   ]
 [184.68106  ]
 [  3.5558047]
 [ -0.9981456]]
[[611.27924  ]
 [182.69493  ]
 [  3.6411345]
 [ -1.2120137]]
[[614.7562   ]
 [180.4868   ]
 [  3.6056094]
 [ -1.4276464]]
[[617.9

 [ 2.5519319e+00]]
[[ 3.3724643e+02]
 [ 1.4767294e+02]
 [-1.8148805e-01]
 [ 2.5145917e+00]]
[[ 3.3750781e+02]
 [ 1.5037975e+02]
 [-8.5617222e-02]
 [ 2.5562005e+00]]
[[3.38299164e+02]
 [1.53300476e+02]
 [1.04222015e-01]
 [2.63511062e+00]]
[[3.3940298e+02]
 [1.5575899e+02]
 [3.2060596e-01]
 [2.5968835e+00]]
[[340.07443  ]
 [158.49751  ]
 [  0.3965595]
 [  2.6275456]]
[[341.60266   ]
 [161.42036   ]
 [  0.64153427]
 [  2.691473  ]]
[[343.65314  ]
 [163.86479  ]
 [  0.9465288]
 [  2.6379933]]
[[345.39124  ]
 [167.16995  ]
 [  1.1178795]
 [  2.7824168]]
[[347.4546   ]
 [170.44019  ]
 [  1.3225499]
 [  2.8880172]]
[[349.0977   ]
 [173.65721  ]
 [  1.3919382]
 [  2.959238 ]]
[[351.01993  ]
 [176.81792  ]
 [  1.5067323]
 [  3.0028484]]
[[353.10263  ]
 [180.51547  ]
 [  1.6314192]
 [  3.1532354]]
[[355.26144  ]
 [183.95346  ]
 [  1.7455844]
 [  3.214878 ]]
[[358.02878  ]
 [187.7834   ]
 [  1.9667671]
 [  3.348021 ]]
[[361.15405  ]
 [191.25873  ]
 [  2.21755  ]
 [  3.3755772]]
[[363.28104  ]
 [1

 [  1.2851617]]
[[521.56415  ]
 [177.6404   ]
 [  3.4728866]
 [  1.1755488]]
[[524.7055    ]
 [177.85188   ]
 [  3.4011145 ]
 [  0.96685416]]
[[527.69196  ]
 [178.31808  ]
 [  3.3113587]
 [  0.8584758]]
[[530.5966   ]
 [178.98962  ]
 [  3.2233267]
 [  0.8180084]]
[[533.4693   ]
 [179.81374  ]
 [  3.1474235]
 [  0.8193285]]
[[536.3409    ]
 [180.15483   ]
 [  3.0877182 ]
 [  0.71580327]]
[[539.2283    ]
 [180.77963   ]
 [  3.0443506 ]
 [  0.69610536]]
[[542.1385   ]
 [181.01755  ]
 [  3.0153093]
 [  0.5969189]]
[[5.4507239e+02]
 [1.8101645e+02]
 [2.9976904e+00]
 [4.6746433e-01]]
[[5.4802753e+02]
 [1.8088654e+02]
 [2.9884810e+00]
 [3.3814955e-01]]
[[5.5099982e+02]
 [1.8070366e+02]
 [2.9849789e+00]
 [2.2536261e-01]]
[[5.5398486e+02]
 [1.8051549e+02]
 [2.9850023e+00]
 [1.3584162e-01]]
[[5.5697876e+02]
 [1.8034837e+02]
 [2.9869280e+00]
 [7.0260197e-02]]
[[5.5997815e+02]
 [1.8021390e+02]
 [2.9896302e+00]
 [2.5939398e-02]]
[[ 5.6298065e+02]
 [ 1.7952643e+02]
 [ 2.9924102e+00]
 [-1.2849523e-01

 [-1.2448027e-01]]
[[ 4.7687704e+02]
 [ 5.6769810e+01]
 [-2.8797545e+00]
 [-9.1861360e-02]]
[[ 4.7406955e+02]
 [ 5.6813232e+01]
 [-2.8641119e+00]
 [-6.2576070e-02]]
[[ 4.7057684e+02]
 [ 5.6860420e+01]
 [-3.0001822e+00]
 [-3.8815107e-02]]
[[ 4.6723764e+02]
 [ 5.6903637e+01]
 [-3.0735693e+00]
 [-2.1057475e-02]]
[[ 4.6343671e+02]
 [ 5.6939213e+01]
 [-3.2310245e+00]
 [-8.7979631e-03]]
[[ 4.5994901e+02]
 [ 5.6966141e+01]
 [-3.2865832e+00]
 [-1.0644874e-03]]
[[ 4.5610468e+02]
 [ 5.6984974e+01]
 [-3.4073176e+00]
 [ 3.2431581e-03]]
[[ 4.5263586e+02]
 [ 5.6997047e+01]
 [-3.4206347e+00]
 [ 5.1548094e-03]]
[[ 4.4884152e+02]
 [ 5.7003937e+01]
 [-3.5015306e+00]
 [ 5.5304426e-03]]
[[ 4.4425772e+02]
 [ 5.7007153e+01]
 [-3.7358129e+00]
 [ 5.0295987e-03]]
[[ 4.3978275e+02]
 [ 5.6420269e+01]
 [-3.8958228e+00]
 [-1.2310247e-01]]
[[ 4.3542691e+02]
 [ 5.6050171e+01]
 [-3.9954052e+00]
 [-1.7656998e-01]]
[[ 4.3118060e+02]
 [ 5.5844116e+01]
 [-4.0497174e+00]
 [-1.8295284e-01]]
[[ 4.2584933e+02]
 [ 5.5752777e+

[[124.18183   ]
 [ 85.555145  ]
 [ -0.77772576]
 [  0.66705066]]
[[123.29724   ]
 [ 86.48364   ]
 [ -0.80085874]
 [  0.72364604]]
[[122.32169   ]
 [ 88.09846   ]
 [ -0.83867437]
 [  0.91656023]]
[[121.29396  ]
 [ 89.54486  ]
 [ -0.8796009]
 [  1.0312564]]
[[120.8293    ]
 [ 90.843605  ]
 [ -0.78977704]
 [  1.0891602 ]]
[[120.13985  ]
 [ 92.61239  ]
 [ -0.7680602]
 [  1.2362792]]
[[119.2896    ]
 [ 93.48876   ]
 [ -0.78585184]
 [  1.1583699 ]]
[[118.92126   ]
 [ 94.94759   ]
 [ -0.69547284]
 [  1.2234107 ]]
[[117.68436  ]
 [ 96.201805 ]
 [ -0.8126771]
 [  1.230078 ]]
[[117.05718  ]
 [ 97.900986 ]
 [ -0.7725203]
 [  1.331626 ]]
[[116.25106   ]
 [ 99.2908    ]
 [ -0.77979517]
 [  1.3442229 ]]
[[115.323715  ]
 [101.63953   ]
 [ -0.81173563]
 [  1.5616707 ]]
[[114.90943  ]
 [104.00076  ]
 [ -0.7256973]
 [  1.734753 ]]
[[114.23696 ]
 [106.32278 ]
 [ -0.714175]
 [  1.861878]]
[[113.38352  ]
 [108.582664 ]
 [ -0.7443217]
 [  1.9480358]]
[[112.4138   ]
 [111.36368  ]
 [ -0.7931142]
 [  2.128352

 [  2.3238993]]
[[270.00778  ]
 [520.2674   ]
 [  0.7713599]
 [  2.341324 ]]
[[270.77457  ]
 [522.4516   ]
 [  0.7703699]
 [  2.3073056]]
[[271.0897   ]
 [525.0812   ]
 [  0.6718279]
 [  2.3770742]]
[[271.70883  ]
 [527.4106   ]
 [  0.6604172]
 [  2.3667467]]
[[271.95267  ]
 [529.536    ]
 [  0.5702381]
 [  2.3145113]]
[[2.7196301e+02]
 [5.3153552e+02]
 [4.4903779e-01]
 [2.2463188e+00]]
[[2.7184607e+02]
 [5.3346710e+02]
 [3.2652128e-01]
 [2.1781886e+00]]
[[2.7167535e+02]
 [5.3537079e+02]
 [2.1888256e-01]
 [2.1187630e+00]]
[[2.7149731e+02]
 [5.3785931e+02]
 [1.3296260e-01]
 [2.1988125e+00]]
[[2.7133801e+02]
 [5.4014081e+02]
 [6.9693208e-02]
 [2.2167108e+00]]
[[2.7120908e+02]
 [5.4227478e+02]
 [2.6690520e-02]
 [2.1987970e+00]]
[[2.7111288e+02]
 [5.4489978e+02]
 [9.1440532e-05]
 [2.2910609e+00]]
[[ 2.7104663e+02]
 [ 5.4724976e+02]
 [-1.4269966e-02]
 [ 2.3038111e+00]]
[[ 2.7100494e+02]
 [ 5.4940680e+02]
 [-2.0202441e-02]
 [ 2.2720366e+00]]
[[ 2.7098181e+02]
 [ 5.5143976e+02]
 [-2.0831408e-

 [  1.1190485]]
[[226.58434  ]
 [730.03815  ]
 [  3.5523927]
 [  1.1440208]]
[[229.2056   ]
 [730.5721   ]
 [  3.3508303]
 [  1.0119456]]
[[231.2602    ]
 [731.2478    ]
 [  3.0702295 ]
 [  0.93916404]]
[[233.58981  ]
 [732.0413   ]
 [  2.9099052]
 [  0.9076381]]
[[235.56537  ]
 [732.9247   ]
 [  2.707646 ]
 [  0.9023812]]
[[237.35304  ]
 [733.2836   ]
 [  2.5084963]
 [  0.7847411]]
[[238.47864   ]
 [733.9017    ]
 [  2.2091372 ]
 [  0.74865705]]
[[239.81877  ]
 [734.7081   ]
 [  2.0210218]
 [  0.7611665]]
[[2.4077089e+02]
 [7.3505310e+02]
 [1.7896339e+00]
 [6.7107671e-01]]
[[2.4151976e+02]
 [7.3569293e+02]
 [1.5643376e+00]
 [6.6432112e-01]]
[[2.4219092e+02]
 [7.3595001e+02]
 [1.3709905e+00]
 [5.7616484e-01]]
[[2.4286200e+02]
 [7.3655554e+02]
 [1.2194794e+00]
 [5.8252442e-01]]
[[2.4298717e+02]
 [7.3739929e+02]
 [9.8259193e-01]
 [6.3906932e-01]]
[[2.4280190e+02]
 [7.3839142e+02]
 [7.2978032e-01]
 [7.1549267e-01]]
[[2.4247269e+02]
 [7.3946454e+02]
 [5.0053942e-01]
 [7.9291767e-01]]
[[2.4

 [ 1.3177629e-02]]
[[ 5.2906110e+02]
 [ 7.4098944e+02]
 [-7.0891747e+00]
 [ 2.0500043e-02]]
[[ 5.1370813e+02]
 [ 7.4101617e+02]
 [-8.8780575e+00]
 [ 2.1843392e-02]]
[[ 4.9677371e+02]
 [ 7.4102850e+02]
 [-1.0622035e+01]
 [ 1.9785661e-02]]
[[ 4.7864450e+02]
 [ 7.4103156e+02]
 [-1.2247133e+01]
 [ 1.6159397e-02]]
[[ 4.6014154e+02]
 [ 7.4102917e+02]
 [-1.3601349e+01]
 [ 1.2144880e-02]]
[[ 4.4234305e+02]
 [ 7.4102417e+02]
 [-1.4509911e+01]
 [ 8.4332004e-03]]
[[ 4.2586841e+02]
 [ 7.4101843e+02]
 [-1.4935220e+01]
 [ 5.3582522e-03]]
[[ 4.1042279e+02]
 [ 7.4101294e+02]
 [-1.5045700e+01]
 [ 3.0132157e-03]]
[[ 3.9806714e+02]
 [ 7.4100830e+02]
 [-1.4463378e+01]
 [ 1.3670312e-03]]
[[ 3.8767825e+02]
 [ 7.4100476e+02]
 [-1.3581365e+01]
 [ 3.1098837e-04]]
[[ 3.8133847e+02]
 [ 7.4100226e+02]
 [-1.2013766e+01]
 [-2.9468327e-04]]
[[ 3.7852908e+02]
 [ 7.4100061e+02]
 [-1.0021274e+01]
 [-5.8198906e-04]]
[[ 3.7877557e+02]
 [ 7.4099963e+02]
 [-7.7985868e+00]
 [-6.5963925e-04]]
[[ 3.8051221e+02]
 [ 7.4099921e+

 [-1.2920221e+00]]
[[ 7.1341541e+02]
 [ 4.7050171e+02]
 [-2.6846167e-01]
 [-1.2283684e+00]]
[[ 7.1290283e+02]
 [ 4.6897849e+02]
 [-3.2131040e-01]
 [-1.2921969e+00]]
[[ 7.1263861e+02]
 [ 4.6769894e+02]
 [-3.0894849e-01]
 [-1.2894597e+00]]
[[ 7.1254205e+02]
 [ 4.6658643e+02]
 [-2.6297179e-01]
 [-1.2511587e+00]]
[[ 7.1196051e+02]
 [ 4.6557831e+02]
 [-3.3193293e-01]
 [-1.1985430e+00]]
[[ 7.1165179e+02]
 [ 4.6462759e+02]
 [-3.2690898e-01]
 [-1.1448945e+00]]
[[ 7.1152954e+02]
 [ 4.6370157e+02]
 [-2.8260952e-01]
 [-1.0975162e+00]]
[[ 7.1152338e+02]
 [ 4.6277945e+02]
 [-2.2275674e-01]
 [-1.0595491e+00]]
[[ 7.1158075e+02]
 [ 4.6184952e+02]
 [-1.6211969e-01]
 [-1.0314902e+00]]
[[ 7.1107727e+02]
 [ 4.6090646e+02]
 [-2.3600386e-01]
 [-1.0123456e+00]]
[[ 7.1079584e+02]
 [ 4.5994907e+02]
 [-2.4583438e-01]
 [-1.0004456e+00]]
[[ 7.1066998e+02]
 [ 4.5897858e+02]
 [-2.1986039e-01]
 [-9.9396569e-01]]
[[ 7.1064410e+02]
 [ 4.5799719e+02]
 [-1.7787492e-01]
 [-9.9124014e-01]]
[[ 7.1067542e+02]
 [ 4.5700760e+

 [-1.0851151e+00]]
[[ 6.9085492e+02]
 [ 3.2483026e+02]
 [-3.9912367e-01]
 [-1.0589974e+00]]
[[ 6.9054108e+02]
 [ 3.2387100e+02]
 [-3.8066623e-01]
 [-1.0374029e+00]]
[[ 6.9043011e+02]
 [ 3.2290939e+02]
 [-3.2228103e-01]
 [-1.0209914e+00]]
[[ 6.8985504e+02]
 [ 3.2194165e+02]
 [-3.7700114e-01]
 [-1.0094643e+00]]
[[ 6.8956323e+02]
 [ 3.2096646e+02]
 [-3.5855922e-01]
 [-1.0020409e+00]]
[[ 6.8887366e+02]
 [ 3.1939642e+02]
 [-4.3021482e-01]
 [-1.1249961e+00]]
[[ 6.8851770e+02]
 [ 3.1803845e+02]
 [-4.1414124e-01]
 [-1.1754298e+00]]
[[ 6.8838702e+02]
 [ 3.1684042e+02]
 [-3.5278204e-01]
 [-1.1803218e+00]]
[[ 6.8780676e+02]
 [ 3.1575388e+02]
 [-4.0202004e-01]
 [-1.1600201e+00]]
[[ 6.8751831e+02]
 [ 3.1473853e+02]
 [-3.7743598e-01]
 [-1.1287076e+00]]
[[ 6.8742395e+02]
 [ 3.1376349e+02]
 [-3.1615445e-01]
 [-1.0954423e+00]]
[[ 6.8744635e+02]
 [ 3.1280707e+02]
 [-2.4286819e-01]
 [-1.0653528e+00]]
[[ 6.8694110e+02]
 [ 3.1185510e+02]
 [-2.9965380e-01]
 [-1.0408076e+00]]
[[ 6.8608838e+02]
 [ 3.1031174e+

 [-1.3679521e+00]]
[[ 7.1436151e+02]
 [ 1.9163934e+02]
 [-5.9767538e-01]
 [-1.3702040e+00]]
[[ 7.1413910e+02]
 [ 1.9048109e+02]
 [-5.1644552e-01]
 [-1.3243204e+00]]
[[ 7.1412860e+02]
 [ 1.8887402e+02]
 [-4.0691990e-01]
 [-1.3855263e+00]]
[[ 7.1364612e+02]
 [ 1.8756253e+02]
 [-4.2328081e-01]
 [-1.3694993e+00]]
[[ 7.1284308e+02]
 [ 1.8645013e+02]
 [-5.0548130e-01]
 [-1.3138435e+00]]
[[ 7.1242981e+02]
 [ 1.8487175e+02]
 [-4.8551744e-01]
 [-1.3711106e+00]]
[[ 7.1227942e+02]
 [ 1.8357600e+02]
 [-4.1297662e-01]
 [-1.3547943e+00]]
[[ 7.1228992e+02]
 [ 1.8247038e+02]
 [-3.2130277e-01]
 [-1.3008527e+00]]
[[ 7.1179822e+02]
 [ 1.8089308e+02]
 [-3.5818663e-01]
 [-1.3606957e+00]]
[[ 7.1097095e+02]
 [ 1.7959523e+02]
 [-4.5973757e-01]
 [-1.3470933e+00]]
[[ 7.1052826e+02]
 [ 1.7848602e+02]
 [-4.5604143e-01]
 [-1.2955977e+00]]
[[ 7.1034949e+02]
 [ 1.7631708e+02]
 [-3.9602557e-01]
 [-1.4846526e+00]]
[[ 7.1033575e+02]
 [ 1.7464607e+02]
 [-3.1326598e-01]
 [-1.5249919e+00]]
[[ 7.1041284e+02]
 [ 1.7274138e+

[[ 5.9671167e+02]
 [ 1.8628738e+01]
 [-2.1650212e+00]
 [-1.4588155e-01]]
[[ 5.9471606e+02]
 [ 1.8701050e+01]
 [-2.1283393e+00]
 [-9.8648869e-02]]
[[ 5.9275458e+02]
 [ 1.8778095e+01]
 [-2.0922165e+00]
 [-6.0615797e-02]]
[[ 5.9021887e+02]
 [ 1.8847895e+01]
 [-2.1882155e+00]
 [-3.2384608e-02]]
[[ 5.8731433e+02]
 [ 1.8904903e+01]
 [-2.3432829e+00]
 [-1.3033448e-02]]
[[ 5.8478632e+02]
 [ 1.8947760e+01]
 [-2.3832729e+00]
 [-9.3505956e-04]]
[[ 5.8194092e+02]
 [ 1.8977526e+01]
 [-2.4833097e+00]
 [ 5.7110707e-03]]
[[ 5.7890460e+02]
 [ 1.8996445e+01]
 [-2.6030154e+00]
 [ 8.5702967e-03]]
[[ 5.7576996e+02]
 [ 1.8419397e+01]
 [-2.7181008e+00]
 [-1.1819950e-01]]
[[ 5.7318707e+02]
 [ 1.8054714e+01]
 [-2.6888344e+00]
 [-1.7155612e-01]]
[[ 5.7038831e+02]
 [ 1.7851004e+01]
 [-2.7126343e+00]
 [-1.7851697e-01]]
[[ 5.6803516e+02]
 [ 1.7760054e+01]
 [-2.6348133e+00]
 [-1.5956134e-01]]
[[ 5.6537970e+02]
 [ 1.7741510e+01]
 [-2.6392860e+00]
 [-1.2903485e-01]]
[[ 5.6251721e+02]
 [ 1.7176685e+01]
 [-2.6875923e+0

 [ 1.5920303e-05]]
[[ 2.3669041e+02]
 [ 2.3000050e+01]
 [-1.9405776e+00]
 [ 5.7287125e-06]]
[[ 2.3493179e+02]
 [ 2.3000027e+01]
 [-1.9011915e+00]
 [-5.8036716e-07]]
[[ 2.3307068e+02]
 [ 2.3000011e+01]
 [-1.8925141e+00]
 [-3.9775641e-06]]
[[ 2.3113663e+02]
 [ 2.3000000e+01]
 [-1.9015059e+00]
 [-5.4335055e-06]]
[[ 2.2915483e+02]
 [ 2.2999994e+01]
 [-1.9188880e+00]
 [-5.4335055e-06]]
[[ 2.2714494e+02]
 [ 2.2999992e+01]
 [-1.9385859e+00]
 [-4.7055346e-06]]
[[ 2.2512117e+02]
 [ 2.2999992e+01]
 [-1.9570259e+00]
 [-3.7349068e-06]]
[[ 2.2368065e+02]
 [ 2.2999994e+01]
 [-1.8452193e+00]
 [-2.7642791e-06]]
[[ 2.2143541e+02]
 [ 2.2999994e+01]
 [-1.9318129e+00]
 [-2.0363084e-06]]
[[ 2.1924770e+02]
 [ 2.2999994e+01]
 [-1.9872066e+00]
 [-1.3083377e-06]]
[[ 2.1770262e+02]
 [ 2.2999996e+01]
 [-1.8914969e+00]
 [-5.8036699e-07]]
[[ 2.1598589e+02]
 [ 2.2999998e+01]
 [-1.8536638e+00]
 [-9.5053167e-08]]
[[ 2.1414052e+02]
 [ 2.2999998e+01]
 [-1.8518682e+00]
 [ 1.4760374e-07]]
[[ 2.1279378e+02]
 [ 2.2999998e+

 [  2.089787  ]]
[[ 75.14156  ]
 [148.91844  ]
 [  0.4524198]
 [  2.142659 ]]
[[ 75.51079  ]
 [150.52133  ]
 [  0.4344098]
 [  2.0258129]]
[[ 75.645004  ]
 [152.24075   ]
 [  0.36942628]
 [  1.9594879 ]]
[[ 76.22306   ]
 [154.05875   ]
 [  0.41458958]
 [  1.9288588 ]]
[[ 77.09426   ]
 [155.95308   ]
 [  0.51343346]
 [  1.9213849 ]]
[[ 78.14     ]
 [157.90204  ]
 [  0.6286635]
 [  1.9273543]]
[[ 78.686386 ]
 [159.88696  ]
 [  0.6108525]
 [  1.9398172]]
[[ 79.48155  ]
 [161.8932   ]
 [  0.6507511]
 [  1.954198 ]]
[[ 80.437     ]
 [163.91017   ]
 [  0.71670914]
 [  1.9677849 ]]
[[ 80.89687  ]
 [165.93076  ]
 [  0.6611135]
 [  1.979213 ]]
[[ 81.61859  ]
 [167.95067  ]
 [  0.6742335]
 [  1.9880224]]
[[ 82.51698  ]
 [169.96768  ]
 [  0.7227571]
 [  1.9942986]]
[[ 83.52361  ]
 [172.56868  ]
 [  0.7842075]
 [  2.1256323]]
[[ 84.000084  ]
 [175.5355    ]
 [  0.71759236]
 [  2.3077278 ]]
[[ 84.71763  ]
 [178.11623  ]
 [  0.7175817]
 [  2.3668215]]
[[ 85.60116  ]
 [181.00246  ]
 [  0.7535056]
 [ 

 [  0.6794031]]
[[149.5122    ]
 [408.01514   ]
 [  0.76633716]
 [  0.5758061 ]]
[[150.56523   ]
 [407.99432   ]
 [  0.8283952 ]
 [  0.44665825]]
[[151.06143  ]
 [408.44434  ]
 [  0.7564853]
 [  0.4473804]]
[[1.5178181e+02]
 [4.0863055e+02]
 [7.4866980e-01]
 [3.9085105e-01]]
[[1.5265871e+02]
 [4.0865082e+02]
 [7.7642781e-01]
 [3.1063062e-01]]
[[1.5304800e+02]
 [4.0916666e+02]
 [6.9262576e-01]
 [3.5505432e-01]]
[[153.71242   ]
 [410.01144   ]
 [  0.68651855]
 [  0.46107402]]
[[154.56795  ]
 [410.4658   ]
 [  0.7231054]
 [  0.4596181]]
[[155.54498   ]
 [411.23938   ]
 [  0.778072  ]
 [  0.52758145]]
[[156.59047   ]
 [411.62628   ]
 [  0.8359602 ]
 [  0.49712703]]
[[157.0794    ]
 [412.34305   ]
 [  0.76083946]
 [  0.54467225]]
[[157.79358   ]
 [412.68613   ]
 [  0.7507372 ]
 [  0.50102895]]
[[158.66562   ]
 [412.7839    ]
 [  0.7769985 ]
 [  0.41373846]]
[[159.63913  ]
 [413.32465  ]
 [  0.8195392]
 [  0.4412305]]
[[160.67075   ]
 [414.1628    ]
 [  0.8654499 ]
 [  0.52715045]]
[[161.729

 [-5.518043e-03]]
[[ 5.3544977e+02]
 [ 5.5101447e+02]
 [ 2.6900306e+00]
 [-1.1675704e-02]]
[[ 5.3787549e+02]
 [ 5.5099432e+02]
 [ 2.6328101e+00]
 [-1.3516014e-02]]
[[ 5.4058142e+02]
 [ 5.5098413e+02]
 [ 2.6486506e+00]
 [-1.2793868e-02]]
[[ 5.4347607e+02]
 [ 5.5098065e+02]
 [ 2.7019031e+00]
 [-1.0774963e-02]]
[[ 5.4589819e+02]
 [ 5.5098126e+02]
 [ 2.6413360e+00]
 [-8.3134510e-03]]
[[ 5.4859937e+02]
 [ 5.5098395e+02]
 [ 2.6542881e+00]
 [-5.9295893e-03]]
[[ 5.5148914e+02]
 [ 5.5098743e+02]
 [ 2.7052577e+00]
 [-3.8873886e-03]]
[[ 5.5449463e+02]
 [ 5.5099097e+02]
 [ 2.7702508e+00]
 [-2.2877944e-03]]
[[ 5.5756189e+02]
 [ 5.5099396e+02]
 [ 2.8345451e+00]
 [-1.1385713e-03]]
[[ 5.6065387e+02]
 [ 5.5099640e+02]
 [ 2.8902824e+00]
 [-3.6983422e-04]]
[[5.6374756e+02]
 [5.5099811e+02]
 [2.9343178e+00]
 [8.8302026e-05]]
[[5.6741791e+02]
 [5.5099927e+02]
 [3.0936561e+00]
 [3.2901767e-04]]
[[5.7085370e+02]
 [5.5100006e+02]
 [3.1677110e+00]
 [4.2219792e-04]]
[[5.7469507e+02]
 [5.5100049e+02]
 [3.3135459